In [2]:
import numpy as np 
import pandas as pd
import seaborn as sns
import tensorflow as tf

In [4]:
class Multiple_Linear_Regression:
    
    def __init__(self):
        self.coef_=None
        self.intercept_=None
    
    def fit(self,X_train,y_train):
        X_train= np.insert(X_train,0,1,axis=1)
        betas = np.linalg.inv(np.dot(X_train.T,X_train)).dot(X_train.T).dot(y_train)
        self.intercept_ = betas[0]
        self.coef_ = betas[1:]
    def predict(self,X_test):
        y_pred=np.dot(X_test,self.coef_) + self.intercept_
        return y_pred
    

In [7]:
from sklearn.datasets import load_diabetes

In [8]:
X,y = load_diabetes(return_X_y=True)

In [9]:
X

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]])

In [10]:
y

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

In [11]:
lr=Multiple_Linear_Regression()

In [12]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)


In [13]:
lr.fit(X_train,y_train)

In [14]:
np.insert(X_test,0,1,axis=1)

array([[ 1.00000000e+00,  6.71362140e-02, -4.46416365e-02,
         3.49435453e-03,  3.56437894e-02,  4.93412959e-02,
         3.12535626e-02,  7.07299263e-02, -3.94933829e-02,
        -6.11735305e-04,  1.96328371e-02],
       [ 1.00000000e+00, -7.81653240e-02,  5.06801187e-02,
         7.78633876e-02,  5.28580443e-02,  7.82363060e-02,
         6.44472995e-02,  2.65502726e-02, -2.59226200e-03,
         4.06728289e-02, -9.36191133e-03],
       [ 1.00000000e+00,  4.17084449e-02,  5.06801187e-02,
        -1.48284507e-02, -1.71351160e-02, -5.69681839e-03,
         8.39372489e-03, -1.39477432e-02, -1.85423958e-03,
        -1.18968513e-02,  3.06440941e-03],
       [ 1.00000000e+00, -4.54724779e-02, -4.46416365e-02,
        -4.82406250e-02, -1.94418262e-02, -1.93006962e-04,
        -1.60318551e-02,  6.70482885e-02, -3.94933829e-02,
        -2.47954290e-02,  1.96328371e-02],
       [ 1.00000000e+00,  9.01559883e-03,  5.06801187e-02,
         6.92408910e-02,  5.97437462e-02,  1.76943802e-02,
  

In [15]:
y_test[0]

73.0

In [16]:
a=lr.predict(X_test)

In [17]:
a[0]

154.12138809538368

In [18]:
from sklearn.metrics import r2_score
r2_score(y_test,a)

0.4399338661568972